### ISSUE TITLE
no wait for start button release

### ISSUE THREAD

**Issue by makapuf** [lowagner/bitbox-mmat#1]
if you keep the start button pressed, all screens flash and go the next one quickly !
if you release it quickly, all is OK.

**Comment by lowagner** [comment]
please check now if everything is alright.

**Comment by makapuf** [comment]
I checked and traced the code. It comes from the fact that kbd_emulate_gamepad  updates the buttons based on keyboard events, but those are already written before/asynchronously if you use the real gamepad. So as you update the previous_gamepad first with the real valuen then call keyboard emulate gamepad (which does nothing if you're on a gamepad) and compare this to current value ... finding no diferences. The fix is to move the update previous status loop at the end of read_presses.

**Comment by lowagner** [comment]
great, thanks for bug-testing and debugging!
